#!/bin/bash
# Place in .git/hooks/. and also chmod +x pre-commit (only if linux)
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi
